### ISSUE TITLE
Execute Python error

### ISSUE THREAD

**Issue by kaiping39** [howl-anderson/tools_for_corpus_of_people_daily#1]
Hi, An error occurred while executing python "python ./conll_to_char_crfpp.py", err-msg "ImportError: No module named 'tokenizer_tools'". How should I import BILUOEncoderDecoder? tks.

**Comment by howl-anderson** [comment]
Do you already install dependencies by `pip install -r requirements.txt` ?

**Comment by kaiping39** [comment]
> Do you already install dependencies by `pip install -r requirements.txt` ?

Yes, it's work now, many tks for your help.
